require_relative 'orb_configuration/version'
require 'orb_logger'

LOG = OrbLogger::OrbLogger.new

# rake-notes are supported, format: TODO: , FIXME: ,:OPTIMIZE
# TODO: ADD DESCRIPTION
module OrbConfiguration
  # TODO: ADD DESCRIPTION
  attr_accessor :logger
  class Main
    def initialize
      @logger = LOG || OrbLogger::OrbLogger.new
      # TODO: replace with whatever progname you want.  The easiest way to get a pertinent progname in your log is to
      # set the progname to self.class.
      @logger.progname = self.class
    end
    # TODO: ADD DESCRIPTION
    def run
      @logger.info 'Programatically generated by orb-archetyper.'
    end
  end
end
